---
title: "SRS: design based theory"
author: "Stat 260, St. Clair"
subtitle: "Week 2 (2.8)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

## "Intro stats" vs. "design-based"

**An Intro Stats story**: Responses are randomly selected from a "normal population"

  -  the population is infinite
  
  - the observed value $Y_i$ is **random**: $Y_i \sim N(\mu, \sigma^2)$
  
---

## "Intro stats" vs. "design-based"

**Design-based story**: 

  - Responses are **fixed** values (not random, just unknown)
  
  -  the population is finite
  
  - the **sampling design** induces randomness, who is picked for the sample is random (not their response)
  
---

## Design-based derivations

Use the design-based perspective to prove that $\bar{y}$ is an unbiased estimator of the population mean $\bar{y}_{\mathcal{U}}$ when the design is a SRS.

---

---

## Design-based derivations

Use the design-based perspective to prove that $\hat{t}_{HT} = \sum y_i/\pi_i$ is an unbiased estimator of the population total.


---

---

## SRS variance

Prove that for a SRS:
$$
SE(\hat{\bar{y}}_{\mathcal{U}} ) = \dfrac{SE(\hat{t})}{N} = \sqrt{\left(1-\dfrac{n}{N} \right) \dfrac{s^2}{n}}
$$

---
