---
title: "Ratio estimation - why and when"
author: "Stat 260, St. Clair"
subtitle: "Week 4 (4.1 up to 4.1.2)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(collapse=TRUE, prompt=TRUE, comment=NULL, message = FALSE, warning = FALSE, fig.height = 7, fig.width = 11)
library(dplyr)
library(knitr)
```


## Example 1: revisit petition
Signatures to a petition were collected on 676 sheets of paper. Along with each signature is a record of whether they are registered to vote. 

How do you measure the proportion of signatures that belong to registered voters on all sheets?

---

## Example 1: revisit petition
You take a SRS of 50 sheets and find 1515 signatures, 771 of which are from registered voters.  


Use this information to estimate the proportion of all signatures that are from registered voters. 

---

## Example 1: revisit petition
The estimated proportion signatures belongin to registered voters is
$$
\hat{p} = \dfrac{771}{1515} = 0.5089
$$

Why can we **not use a SRS SE formula** to measure the variability of this estimate?

---

## Ratio estimation: for a ratio parameter

- For each sampling unit, we measure two variables: $x_i$ and $y_i$

- **Ratio Parameter** Suppose our parameter of interest looks lik
$$B = \dfrac{\sum_{i=1}^N y_i}{\sum_{i=1}^N x_i} = \dfrac{t_y}{t_x} = \dfrac{\bar{y}_{\mathcal{U}}}{\bar{x}_{\mathcal{U}}}$$

<br>
<br>

- **Estimator** with a SRS of units:
$$\hat{B} = \dfrac{\sum_{i=1}^n y_i}{\sum_{i=1}^n x_i} = \dfrac{\bar{y}}{\bar{x}}$$


<br>
<br>

- SE and bias: next video


---

## Example 2: food costs

If there are $N$ households in the city, how would you form the parameter that measures the average weekly food costs per resident in Northfield if you plan to take a SRS of $n$ households in the city?

---

## Example 3: food costs take 2

Suppose you don't know $N$, the number of households (sampling units) in the population.

You do know $t_{income}$ from IRS records.

If you have a SRS of $n$ households with income recorded, how can you estimate $N$?


---

## Example 3: food spending take 2

How can you estimate the total weekly food costs for all residents of Northfield if you have an SRS of $n$ households and know the total income for all residents.


---

## Ratio estimation for a mean or total

- Suppose we know a population mean or total for an **auxiliary** variable $x$ $$t_x \textrm{ and/or } \bar{x}_{U} \textrm{ are known}$$


- **Population total** for response $y$ can be written
$$
t_y = \dfrac{t_y}{t_x}  t_x = B t_x
$$

<br>



- **Population total** for response $y$ can be written
$$\bar{y}_{\mathcal{U}}=  \dfrac{\bar{y}_{\mathcal{U}}}{\bar{x}_{\mathcal{U}}} \bar{x}_{\mathcal{U}} = B \bar{x}_{\mathcal{U}}$$

<br>




- **Estimators** use an estimated ratio $\hat{B}= \dfrac{\sum_{i=1}^n y_i}{\sum_{i=1}^n x_i} = \dfrac{\bar{y}}{\bar{x}}$



---

## Example 4: a classic

The 1920 census found that the total number of residents living in 196 selected major U.S. cities was 22,919 thousand people. 

We would like to determine the total number of residents living in these cities in 1925 (a year with no census).


who? | 1920 $(x)$ | 1925 $(y)$ 
----------- | ------ | -----
population | $t_x = 22,919$ | $t_y = ??$

---

## Example 4: a classic

A random sample of 49 of these cities was taken in 1925 and for each city in the sample the 1920 and 1925 population sizes (in the thousands) were recorded:

who? | 1920 $(x)$ | 1925 $(y)$ 
----------- | ------ | -----
population | $t_x = 22,919$ | $t_y = ??$
sample |  $\sum_{i=1}^{49} x_i = 5054$ | $\sum_{i=1}^{49} y_i = 6262$

What is a SRS estimate of the total number of people in these 196 cities in 1920? in 1925? 

---

## Example 4: a classic

who? | 1920 $(x)$ | 1925 $(y)$ 
----------- | ------ | -----
population | $t_x = 22,919$ | $t_y = ??$
sample |  $\sum_{i=1}^{49} x_i = 5054$ | $\sum_{i=1}^{49} y_i = 6262$

SRS estimates:
$$\hat{t}_{1920} = 20,216 \ \ \ \ \hat{t}_{1925} = 25,048$$

Does this SRS over or under estimate the 1920 total? Is it likely that the SRS does the same for the 1925 total?



---

## Example 4: a classic


who? | 1920 $(x)$ | 1925 $(y)$ 
----------- | ------ | -----
population | $t_x = 22,919$ | $t_y = ??$
sample |  $\sum_{i=1}^{49} x_i = 5054$ | $\sum_{i=1}^{49} y_i = 6262$

What is a **ratio estimate** of the total number of people in these 196 cities in 1925?  Is this greater or smaller than the SRS estimate?


---

## Calibration weights

- Usual SRS sampling weights are $N/n$

- Ratio estimates of total/mean have an added **calibration weight** of 
$$g_i = \dfrac{t_x}{\hat{t}_x} = \dfrac{\bar{x}_{\mathcal{U}}}{\bar{x}}$$

- These weights adjust the SRS estimate up or down, depending on whether the auxilary mean/total is over- or underestimated in the SRS.



---

## Example 4: a classic


who? | 1920 $(x)$ | 1925 $(y)$ 
----------- | ------ | -----
population | $t_x = 22,919$ | $t_y = ??$
sample |  $\sum_{i=1}^{49} x_i = 5054$ | $\sum_{i=1}^{49} y_i = 6262$

$$\hat{t}_{y, srs} = 25,048 \ \ \ \ \hat{t}_{y,ratio} = 28,397$$

What is the calibration weight for this ratio estimator?