---
title: "Intro to Nonresponse"
author: "Stat 260, St. Clair"
subtitle: "Week 8 (8.1-8.4)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, prompt=TRUE, comment=NULL,tidy.opts=list(width.cutoff=60),tidy=FALSE,eval=TRUE,eval=TRUE, warning=FALSE, message  = FALSE, fig.width = 11, fig.height = 7)
library(dplyr)
library(tidyr)
library(ggplot2)
```


## Quantifying nonresponse bias

Subpopulation | Size | Mean 
------------- | ---- | ----
Respondents   | $N_R$ | $\bar{y}_{R\mathcal{U}}$
Nonrespondents   | $N_M$ | $\bar{y}_{M\mathcal{U}}$
Everyone | $N = N_R + N_M$ | $\bar{y}_{\mathcal{U}} = \dfrac{N_R}{N}\bar{y}_{R\mathcal{U}} + \dfrac{N_M}{N}\bar{y}_{M\mathcal{U}}$

---



## Quantifying nonresponse bias

Subpopulation | Size | Mean 
------------- | ---- | ----
Respondents   | $N_R/N = 0.36$ | $\bar{y}_{R\mathcal{U}} = 36$
Nonrespondents   | $N_M/N = 0.64$ | $\bar{y}_{M\mathcal{U}} = 50$


---

## Types of nonresponse

Mechanism model: 

$$R_i = \left\{ \begin{array}{ll}
1 & \textrm{if unit } i \textrm{ responds} \\
0 & \textrm{if unit } i \textrm{ does not respond}  \end{array} \right.$$

The probability of response is ("phi")
$$
\phi_i = P(R_i = 1)
$$
Variables:

- Response of interest $y_i$ (only observed for respondents)

- Covariates $x_i$ (known for both respondents and nonrespondents)


---

## Types of nonresponse: MCAR

**Missing Completely at Random (MCAR)**

- $\phi_i$ does not depend on $y_i$ or $x_i$ (or design)

- Nonresponse only lowers sample size

- No nonresponse bias since $\bar{y}_{R\mathcal{U}} = \bar{y}_{M\mathcal{U}}$





---

## Types of nonresponse: MAR

**Missing at Random given covariates (MAR)**

- $\phi_i$  depends on $x_i$ but not $y_i$ (given $x_i$)
$$
\phi_i(x_i) = P(R_i = 1 \mid x_i) =  P(R_i = 1 \mid x_i, y_i)
$$

- *ignorable* nonresponse: "Model" $\phi$ given $x$, then nonresponse can be ignored

  - e.g. poststratification



---

## Types of nonresponse: NMAR

**Not Missing at Random (MMAR)**

- $\phi_i$  depends on $x_i$ and $y_i$ 
$$
\phi_i(x_i, y_i) = P(R_i = 1 \mid x_i, y_i)
$$

- *nonignorable* nonresponse

- hard to distinguish MAR and NMAR

- most data is probably NMAR!
