---
title: "Poststratification"
author: "Stat 260, St. Clair"
subtitle: "Week 5 (4.4)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(collapse=TRUE, prompt=TRUE, comment=NULL, message = FALSE, warning = FALSE, fig.height = 7, fig.width = 11)
```




### Idea: Population

You have a population with **known** stratum fractions:
$$\dfrac{N_1}{N}, \dfrac{N_2}{N}, \dotsc, \dfrac{N_H}{N}$$

---


### Idea: Sample Design

You **don't** have the stratification variable in the sampling frame. 

You take a **SRS** of size $n$ and observed

  - response $y_i$
  
  - stratification variable

---

### Idea: Poststratification

**After** the SRS, divide the SRS into strata and calibrate estimates of $t_y, \bar{y}_{\mathcal{U}}$ based on known population stratum characteristics


- divide responses by stratum

- get *domain* estimates for each stratum

- combine domain estimates like you would in a stratified sample


---

### Benefits

- Nonresponse: if related to stratum, poststratification can reduce non-response bias IF
  - within stratum: non-respondents $\approx$ respondents
  
<br>
<br>
<br>

<br>
<br>
<br>

- If $n$ is large, can increase precision over SRS if stratification *would* have been beneficial




---

### Poststratification estimation: mean

- **Parameter**  $\bar{y}_{\mathcal{U}}$ 


- **Estimator** 
$$\bar{y}_{post} = \sum_{h=1}^H \frac{N_h}{N} \bar{y}_h$$

- **SE**:
$$SE(\bar{y}_{post} ) \approx \sqrt{\sum_{h=1}^H \left(\frac{N_h}{N}\right)^2 \left( 1- \frac{n}{N}\right) \left( \frac{n}{n-1}\right)\left( \frac{n_h - 1}{n_h}\right)\frac{s^2_h}{n_h}} \\
\approx \sqrt{\left( 1- \frac{n}{N}\right)\sum_{h=1}^H \frac{N_h}{N}\frac{s^2_h}{n} }$$

---

### Poststratification estimation: proportion


- **Parameter**  $p$ 


- **Estimator** 
$$\hat{p}_{post} =\sum_{h=1}^H \frac{N_h}{N} \hat{p}_h$$

- **SE**: same as mean but with $s^2_h = \dfrac{n_h}{n_h - 1}\hat{p}_h(1-\hat{p}_h)$



---

### Poststratification estimation: total

- **Parameter**  $t = N\bar{y}_{\mathcal{U}}$ 


- **Estimator** 
$$\hat{t}_{post}= N\bar{y}_{post} = \sum_{h=1}^H N_h \bar{y}_h$$

- **SE**:
$$SE(\hat{t}_{post}) = N SE(\bar{y}_{post})$$

---

### Example
The population of$N=1,500$ students. We have a SRS of 200 students and obtained 135 responses to the question *How many hours per week do you devote to study outside of regular class time?* 

|  Female | Male | all 
---- | ------ | ---- | ----
$n_h$ | 104 | 31 | 135 
$\bar{y}_h$ | 12.38  | 8.03 | 11.38
$s_h$ | 6.68 | 5.50 | 6.68

SRS estimate/SE of mean study hours per week?


---

### Example

|  Female | Male | all 
---- | ------ | ---- | ----
$N_h$ | 900 | 600 | 1500
$n_h$ | 104 | 31 | 135 
$\bar{y}_h$ | 12.38  | 8.03 | 11.38
$s_h$ | 6.68 | 5.50 | 6.68

Poststratified estimate/SE of mean study hours per week?



---

### Example


|  Female | Male | all 
---- | ------ | ---- | ----
$N_h$ | 900 | 600 | 1500
$n_h$ | 104 | 31 | 135 
$\bar{y}_h$ | 12.38  | 8.03 | 11.38
$s_h$ | 6.68 | 5.50 | 6.68

$$\bar{y} = 11.38 \ \ \ SE(\bar{y}) = 0.55$$
$$\bar{y}_{post} = 10.64 \ \ \ SE(\bar{y}_{post}) = 0.51$$

Why is the poststratified estimator of mean study hours lower than the SRS?